name: togg_app
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
    sdk: '>=2.7.0 <3.0.0'
dependencies:
    flutter:
        sdk: flutter
    cupertino_icons: ^1.0.2
    get_it: ^4.0.4
    logger: ^0.9.2
    stacked: ^1.7.6
    stacked_services: ^0.5.4+2
    responsive_builder: ^0.2.0+2
    equatable: ^1.2.4
    flutter_screenutil: ^5.3.1
    flutter_svg: ^1.0.2
    dio: ^4.0.4
    shared_preferences: ^2.0.13
    firebase_core: ^1.12.0
    google_maps_flutter: ^2.1.5
    provider: ^4.3.3
    url_launcher: ^6.1.2
    firebase_analytics: ^9.1.9
    firebase_crashlytics: ^2.8.1
    flutter_dotenv: ^5.0.2

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^1.0.0

flutter:
    uses-material-design: true


  # To add assets to your application, add an assets section, like this:
    assets:
        - assets/images/svg/
        - dev.env
        - stage.env
        - prod.env
      
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
      
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
      
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages